# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Ozric
version: "0.1.0"
slug: ozric
description: Example add-on
#url: "https://github.com/jchown/ozric/tree/master/OzricAddon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#init: false
options:
  message: "A message from Ozric..."
schema:
  message: "str?"
homeassistant_api: true
#image: "github.com/jchown/ozric"